const UPDATE_USER_ID = 'UPDATE_USER_ID'
const UPDATE_USER_BIO = 'UPDATE_USER_BIO'
const UPDATE_COMPLETION = 'UPDATE_COMPLETION'
const UPDATE_USER_INFOS = 'UPDATE_USER_INFOS'
const UPDATE_COURSES = 'UPDATE_COURSES'
const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
const UPDATE_COMPLETION_CARD = 'UPDATE_COMPLETION_CARD'
const UPDATE_CHAPTER_AS_COMPLETED = 'UPDATE_CHAPTER_AS_COMPLETED'
const RESET_CHAPTERS_COMPLETION = 'RESET_CHAPTERS_COMPLETION'
const UPDATE_ACTUAL_EXERCISE = 'UPDATE_ACTUAL_EXERCISE'
const UPDATE_KEYBOARD = 'UPDATE_KEYBOARD'
const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'

export default {
  UPDATE_USER_ID,
  UPDATE_USER_BIO,
  UPDATE_COMPLETION,
  UPDATE_USER_INFOS,
  UPDATE_COURSES,
  UPDATE_USER_NAME,
  UPDATE_COMPLETION_CARD,
  UPDATE_CHAPTER_AS_COMPLETED,
  RESET_CHAPTERS_COMPLETION,
  UPDATE_ACTUAL_EXERCISE,
  UPDATE_KEYBOARD,
  UPDATE_USER_EMAIL,
}
